### ISSUE TITLE
Issues on MacOS and Linux: "error TS2304: Cannot find name"

### ISSUE THREAD

**Issue by AaronV-T** [andywer/threads.js#135]
I started using this package on my Windows computer and it worked well for me. Unfortunately, after I committed all my changes neither my coworker could build our project on his Mac neither could our Linux Jenkins server build the project. They fail with the following errors:

> [clean:build] node_modules/threads/dist/transferable.d.ts(5,20): error TS2304: Cannot find name 'Transferable'.
> [clean:build] node_modules/threads/dist/transferable.d.ts(8,48): error TS2304: Cannot find name 'Transferable'.
> [clean:build] node_modules/threads/dist/types/master.d.ts(20,36): error TS2304: Cannot find name 'Transferable'.
> [clean:build] node_modules/threads/dist/types/master.d.ts(21,33): error TS2304: Cannot find name 'EventTarget'.
> [clean:build] node_modules/threads/dist/types/master.d.ts(25,51): error TS2304: Cannot find name 'EventTarget'.
> [clean:build] node_modules/threads/dist/types/worker.d.ts(4,54): error TS2304: Cannot find name 'Transferable'.

We are using Node.js LTS version (10.x) and the packages I had installed were threads 1.0.0-beta.2, and tiny-worker 2.2.0.

**Comment by andywer** [comment]
Thanks for reporting, @AaronV-T. Yes, that's a subtle TypeScript issue.

The errors will go away if you add `"dom"` to `compilerOptions.lib` in your `tsconfig.json` file. I will look into a solution, so you don't need the `dom` lib setting.

**Comment by andywer** [comment]
Try `npm install threads@1.0.0-beta.2-tsconfig`. Should now work without changing your `tsconfig.json`.

**Comment by AaronV-T** [comment]
My code that works with threads `1.0.0-beta.2` throws the following error when I use threads `1.0.0-beta.2-tsconfig`:

> TypeError: events_1.default is not a constructor
> [watch:server]     at new Worker (D:\Dropbox\VisualPhase\vp-hvac\backend\node_modules\threads\dist\master\implementation.node.js:61:28)
> [watch:server]     at Object.<anonymous> (D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:54:66)
> [watch:server]     at step (D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:32:23)
> [watch:server]     at Object.next (D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:13:53)
> [watch:server]     at D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:7:71
> [watch:server]     at new Promise (<anonymous>)
> [watch:server]     at __awaiter (D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:3:12)
> [watch:server]     at D:\Dropbox\VisualPhase\vp-hvac\backend\dist\backend\src\controllers\export.controller.js:50:47
> [watch:server]     at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by andywer** [comment]
Yeah, something was weird with the published pre-release. Can you please try again using `npm i threads@1.0.0-beta.2-tsconfig.2`?

**Comment by AaronV-T** [comment]
Installing `threads@1.0.0-beta.2-tsconfig.2` allowed me to run successfully on my Windows machine, but the Linux build server has the same errors as it did originally:

> 21:25:52 > tsc && npm run copy-static-assets
> 21:25:52 
> 21:26:02 node_modules/threads/dist/transferable.d.ts(5,20): error TS2304: Cannot find name 'Transferable'.
> 21:26:02 node_modules/threads/dist/transferable.d.ts(8,48): error TS2304: Cannot find name 'Transferable'.
> 21:26:02 node_modules/threads/dist/types/master.d.ts(20,36): error TS2304: Cannot find name 'Transferable'.
> 21:26:02 node_modules/threads/dist/types/master.d.ts(21,33): error TS2304: Cannot find name 'EventTarget'.
> 21:26:02 node_modules/threads/dist/types/master.d.ts(25,51): error TS2304: Cannot find name 'EventTarget'.
> 21:26:02 node_modules/threads/dist/types/worker.d.ts(4,54): error TS2304: Cannot find name 'Transferable'.

**Comment by andywer** [comment]
@AaronV-T I think you might still be running a different version of `threads` in CI. There is no reference to `Transferable` in `dist/transferable.d.ts` on line 5 in the `...-tsconfig.2` version: <https://unpkg.com/threads@1.0.0-beta.2-tsconfig.2/dist/transferable.d.ts>

**Comment by andywer** [comment]
Any updates here?

**Comment by andywer** [comment]
Closing due to inactivity. Looks like a one-time package publishing issue that’s been solved.
